import matplotlib.pyplot as plt

file = open("E:/Pulpit/wheelSpeeds.txt", "r")
dataString = file.readlines()

phi1 = list()
phi2 = list()
fid = list()
fi = list()
vGiven = list()
wGiven = list()
vRobot = list()
wRobot = list()
time = list()
X1 = list()
Y1 = list()
X2 = list()
Y2 = list()
P11 = list()
P21 = list()

xlimit = 110

for line in dataString:
    p1, p2, fd, f , vG, wG, vR, wR, t, x1, y1, x2, y2, p11, p21 = line.split()
    phi1.append(float(p1))
    phi2.append(float(p2))
    fid.append(float(fd))
    fi.append(float(f))
    vGiven.append(float(vG))
    wGiven.append(float(wG))
    vRobot.append(float(vR))
    wRobot.append(float(wR))
    time.append(float(t))
    X1.append(float(x1))
    Y1.append(float(y1))
    X2.append(float(x2))
    Y2.append(float(y2))
    P11.append(float(p11))
    P21.append(float(p21))

plt.figure()
plt.plot(time, phi1, label='prawe generator')
plt.plot(time, phi2, label='lewe generator')
plt.plot(time, P11, '--', label='prawe robot')
plt.plot(time, P21, '--', label='lewe robot')
plt.legend(loc="upper right")
plt.grid()
plt.title('Prędkości kół')
plt.xlabel('t[s]')
plt.ylabel('obr/s')
# plt.xlim([0, xlimit])
plt.savefig("predkosciKolPythonRobot1.eps", transparent=True)
plt.savefig("predkosciKolPythonRobot1.png")

plt.figure()
plt.plot(time, fid, label="generator")
plt.plot(time, fi, '--', label="Robot")
plt.legend(loc="upper right")
plt.grid()
plt.title('Kąt obrotu')
plt.xlabel('t[s]')
plt.ylabel('rad')
# plt.xlim([0, xlimit])
plt.savefig("katObrotuPythonRobot1.eps", transparent=True)
plt.savefig("katObrotuPythonRobot1.png")

plt.figure()
plt.plot(time, vGiven, label='generator')
plt.plot(time, vRobot, '--', label='robot')
plt.legend(loc="upper right")
plt.grid()
plt.title('Prędkości liniowe')
plt.xlabel('t[s]')
plt.ylabel('m/s')
plt.xlim([0, xlimit])
plt.savefig("predkosciLinowePythonRobot1.eps", transparent=True)
plt.savefig("predkosciLinowePythonRobot1.png")

plt.figure()
plt.plot(time, wGiven, label="generator")
plt.plot(time, wRobot, '--', label="robot")
plt.legend(loc="upper right")
plt.grid()
plt.title('Prędkości kątowe')
plt.xlabel('t[s]')
plt.ylabel('obr/s')
plt.xlim([0, xlimit])
plt.savefig("predkosciKatkowePythonRobot1.eps", transparent=True)
plt.savefig("predkosciKatkowePythonRobot1.png")

plt.figure()
plt.plot(X1, Y1, label='generator')
plt.plot(X2, Y2, '--', label='robot')
plt.legend(loc="upper right")
plt.grid()
plt.savefig("PozycjaRobot1.eps", transparent=True)
plt.savefig("PozycjaRobot1.png")

plt.show()